[2024-10-17T10:56:08.353+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T10:56:08.390+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: eia_data_pipeline.call_stored_procedure scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T10:56:08.411+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: eia_data_pipeline.call_stored_procedure scheduled__2024-10-16T00:00:00+00:00 [queued]>
[2024-10-17T10:56:08.429+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T10:56:08.485+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): call_stored_procedure> on 2024-10-16 00:00:00+00:00
[2024-10-17T10:56:08.609+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'eia_data_pipeline', 'call_stored_procedure', 'scheduled__2024-10-16T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/new_dag.py', '--cfg-path', '/tmp/tmpo2kkffer']
[2024-10-17T10:56:08.616+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T10:56:08.645+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask call_stored_procedure
[2024-10-17T10:56:08.671+0000] {standard_task_runner.py:72} INFO - Started process 137 to run task
[2024-10-17T10:56:08.949+0000] {task_command.py:467} INFO - Running <TaskInstance: eia_data_pipeline.call_stored_procedure scheduled__2024-10-16T00:00:00+00:00 [running]> on host 7aa864b16460
[2024-10-17T10:56:09.392+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='eia_data_pipeline' AIRFLOW_CTX_TASK_ID='call_stored_procedure' AIRFLOW_CTX_EXECUTION_DATE='2024-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-16T00:00:00+00:00'
[2024-10-17T10:56:09.396+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-17T10:56:09.397+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-17T10:56:09.400+0000] {logging_mixin.py:190} INFO - Current task name:call_stored_procedure state:running start_date:2024-10-17 10:56:08.391690+00:00
[2024-10-17T10:56:09.405+0000] {logging_mixin.py:190} INFO - Dag name:eia_data_pipeline and current dag run status:running
[2024-10-17T10:56:09.410+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T10:57:06.812+0000] {logging_mixin.py:190} INFO - Stored procedure executed successfully.
[2024-10-17T10:57:07.939+0000] {logging_mixin.py:190} INFO - MySQL connection is closed
[2024-10-17T10:57:08.116+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-17T10:57:10.036+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T10:57:10.071+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=eia_data_pipeline, task_id=call_stored_procedure, run_id=scheduled__2024-10-16T00:00:00+00:00, execution_date=20241016T000000, start_date=20241017T105608, end_date=20241017T105710
[2024-10-17T10:57:10.559+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-17T10:57:10.564+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-17T10:57:10.567+0000] {logging_mixin.py:190} INFO - Dag name:eia_data_pipeline queued_at:2024-10-17 10:54:37.506225+00:00
[2024-10-17T10:57:10.569+0000] {logging_mixin.py:190} INFO - Task hostname:7aa864b16460 operator:PythonOperator
[2024-10-17T10:57:11.425+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T10:57:12.292+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T10:57:12.307+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
